repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: poetry run pylint **/*.py
        language: system
        pass_filenames: false

      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false
