name: Create Release on PR Merge with "release" label

on:
  pull_request:
    types: [merged]
    branches:
      - master

jobs:
  create_release:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Read version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create a new tag and release
        uses: gh-cli/actions/create-release@v1
        with:
          tag_name: v${{ env.version }}
          release_name: "Release ${{ env.version }}"
          body: "Release notes for version ${{ env.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
